# Generated by Django 4.2.26 on 2025-11-20 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journey_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('journey_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('emergency', 'Emergency')], default='scheduled', max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('start_address', models.TextField()),
                ('destination_address', models.TextField()),
                ('start_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dest_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dest_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scheduled_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('safety_network', models.JSONField(default=list)),
                ('is_safety_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journeys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('network_strength', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='journey.journey')),
            ],
            options={
                'db_table': 'journey_locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JourneyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('panic', 'Panic Button'), ('voice', 'Voice Trigger'), ('motion', 'Motion Detection'), ('deviation', 'Route Deviation'), ('battery', 'Low Battery'), ('network', 'Poor Network'), ('duration', 'Long Duration')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_alerts', to='journey.journey')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journey_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_capacity', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('route_name', models.CharField(max_length=255)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('max_passengers', models.IntegerField(default=50)),
                ('current_passengers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_journeys', to=settings.AUTH_USER_MODEL)),
                ('journey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_journey', to='journey.journey')),
            ],
            options={
                'verbose_name_plural': 'Group Journeys',
                'db_table': 'group_journeys',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boarding_stop', models.CharField(max_length=255)),
                ('destination_stop', models.CharField(max_length=255)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact_notified', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='journey.groupjourney')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'passengers',
                'unique_together': {('group_journey', 'user')},
            },
        ),
    ]
