# Generated by Django 4.2.26 on 2025-11-20 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('panic_button', 'Panic Button'), ('voice_trigger', 'Voice Trigger'), ('motion_crash', 'Motion/Crash Detection'), ('route_deviation', 'Route Deviation'), ('no_movement', 'No Movement'), ('geofence_breach', 'Geofence Breach'), ('low_battery', 'Low Battery'), ('poor_network', 'Poor Network'), ('long_duration', 'Long Journey Duration'), ('manual', 'Manual Alert')], max_length=20)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('verified', 'Verified'), ('notified', 'Notified'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm'), ('cancelled', 'Cancelled')], default='triggered', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_address', models.TextField(blank=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('network_strength', models.IntegerField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='journey.journey')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PanicButtonPress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('press_count', models.IntegerField(default=1)),
                ('press_duration', models.FloatField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panic_presses', to='journey.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panic_presses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'panic_button_presses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('notification_type', models.CharField(choices=[('websocket', 'WebSocket'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('email', 'Email')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_id', models.CharField(max_length=255, unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subscribed_journeys', models.JSONField(blank=True, default=list)),
                ('subscribed_users', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'websocket_connections',
                'indexes': [models.Index(fields=['user', 'is_active'], name='websocket_c_user_id_0bac24_idx'), models.Index(fields=['connection_id'], name='websocket_c_connect_f81fa3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SafetyNetworkMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_phone', models.CharField(max_length=20)),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('receive_sms', models.BooleanField(default=True)),
                ('receive_whatsapp', models.BooleanField(default=True)),
                ('receive_push', models.BooleanField(default=True)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_network_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_network_members',
                'unique_together': {('user', 'member_phone')},
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['journey', 'status'], name='alerts_journey_f802dd_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='alerts_status_5203b6_idx'),
        ),
    ]
