# Generated by Django 4.2.26 on 2025-11-20 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_type', models.CharField(choices=[('journey_status', 'Journey Status'), ('emergency_info', 'Emergency Information'), ('general_help', 'General Help')], default='journey_status', max_length=20)),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='journey.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceDetectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('safe_word', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('background_noise_level', models.FloatField(blank=True, null=True)),
                ('audio_snippet_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_detection/')),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('error', 'Error')], default='pending', max_length=20)),
                ('triggered_alert', models.BooleanField(default=False)),
                ('user_feedback', models.BooleanField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_events', to='journey.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_detection_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotionDetectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motion_type', models.CharField(choices=[('crash', 'Crash/Impact'), ('sudden_stop', 'Sudden Stop'), ('hard_braking', 'Hard Braking'), ('sharp_turn', 'Sharp Turn'), ('excessive_speed', 'Excessive Speed'), ('no_movement', 'No Movement')], max_length=20)),
                ('acceleration_x', models.FloatField()),
                ('acceleration_y', models.FloatField()),
                ('acceleration_z', models.FloatField()),
                ('g_force', models.FloatField(blank=True, null=True)),
                ('impact_confidence', models.FloatField()),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('triggered_alert', models.BooleanField(default=False)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to='journey.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'motion_detection_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('voice_detection', 'Voice Detection'), ('motion_detection', 'Motion Detection'), ('chatbot_response', 'Chatbot Response'), ('alert_accuracy', 'Alert Accuracy')], max_length=20)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aichatsession')),
                ('motion_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.motiondetectionevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
                ('voice_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.voicedetectionevent')),
            ],
            options={
                'db_table': 'ai_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('assistant', 'AI Response'), ('system', 'System Message')], max_length=20)),
                ('content', models.TextField()),
                ('ai_model', models.CharField(blank=True, max_length=50)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aichatsession')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
